coverage:
  status:
    project:
      default: off
      piaplib:
        target: 45%
        flags: piaplib
      tests:
        target: 50%
        flags: tests

flags:
  piaplib:
    paths:
      - units/PiAP-python-tools/piaplib/
      - units/PiAP-python-tools/piaplib/lint
      - units/PiAP-python-tools/piaplib/pku
      - units/PiAP-python-tools/piaplib/keyring
      - units/PiAP-python-tools/piaplib/book
  tests:
    paths:
      - units/PiAP-python-tools/tests

