linters:
    shellcheck:
        shell: bash
    flake8:
        max-line-length: 100
        max-complexity: 10
        ignore: 'W191,W391'
        exclude: ['.git', '__pycache__', 'docs', '.tox', 'build']
files:
    ignore: ['*/*.pyc', '*.pyc', '*~', '.git', '__pycache__']
