language: generic
sudo: false

branches:
  only:
    - stable
    - master

matrix:
  include:
  - os: linux
    dist: trusty
    language: generic
  - os: linux
    dist: precice
    language: generic
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic

addons:
  hosts:
  - pocket.PiAP.local
  apt:
    packages:
      - php

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 python2.7 python3.5 python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME != osx ] ; then curl -s -o archive.tar.bz2 https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/12.04/x86_64/php-7.1.tar.bz2 && tar xjf archive.tar.bz2 --directory / || true ; fi

install: "true"
# command to run tests
script:
  - make test
