language: generic
sudo: false

branches:
  only:
    - stable
    - staging
    - master

matrix:
  include:
  - os: linux
    dist: trusty
    language: generic
  - os: osx
    osx_image: xcode6.4
    language: generic
  - os: osx
    osx_image: xcode7.3
    language: generic
  - os: osx
    osx_image: xcode8
    language: generic
  - os: osx
    osx_image: xcode8.3
    language: generic
  allow_failures:
  - os: linux
    dist: precice
    language: generic
  - os: linux
    dist: precice
    language: python
  - os: linux
    dist: precice
    language: php7


addons:
  hosts:
  - pocket.PiAP.local

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install pip $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install tox $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.2 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME != osx ] ; then curl --tlsv1.2 -s -o archive.tar.bz2 https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/12.04/x86_64/php-7.1.tar.bz2 && tar xjf archive.tar.bz2 --directory / || true ; fi
  - pip install tox || pip install --upgrade tox || true

install: "true"
# command to run tests
script:
  - time make test-tox
