language: generic

env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)


branches:
  only:
    - stable
    - staging
    - master

matrix:
  include:
  - os: linux
    dist: trusty
    language: generic
  - os: linux
    dist: xenial
    language: generic
  - os: linux
    dist: bionic
    language: generic
  - os: osx
    osx_image: xcode10
    language: shell
  - os: osx
    osx_image: xcode11.1
    language: shell
  - os: osx
    osx_image: xcode11.2
    language: shell
  - os: osx
    osx_image: xcode11.3
    language: shell
  allow_failures:
  - os: linux
    language: python
  - os: linux
    language: php7
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode9
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode10
  - os: osx
    osx_image: xcode10.1
  - os: osx
    osx_image: xcode11
  - os: osx
    osx_image: xcode11.1


addons:
  hosts:
  - pocket.PiAP.local

before_install:
  - echo "travis_fold:start:piap_setup" 2>/dev/null || true
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait git -C "$(brew --repo homebrew/core)" fetch --unshallow || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_retry brew tap homebrew/versions || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then travis_wait brew upgrade || travis_retry brew upgrade || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install php7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install pip $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install tox $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python27 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python@2 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python26 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python34 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.4 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python35 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python@3 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py3.5 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install py2.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.6 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install python3.7 $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install coverage $INSTALL || true ; fi
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install codecov || true ; fi
  - travis_retry pip install tox || pip3 install tox || true ;
  - travis_retry pip install coverage || true ;
  - travis_retry pip install codecov || true ;
  - travis_retry python -m pip install coverage || python -m pip install coverage || true ;
  - travis_retry python -m pip install codecov || python -m pip install codecov || true ;
  - travis_retry python3 -m pip3 install tox || python3 -m pip install tox || true ;
  - travis_retry python3 -m pip3 install coverage || python3 -m pip install coverage || true ;
  - travis_retry python3 -m pip3 install codecov || python3 -m pip install codecov || true ;
  - travis_retry ln -s -f ./units/PiAP-python-tools/requirements.txt ./requirements.txt || true ;
  - travis_retry python3 -m pip install -r requirements.txt || python3 -m pip install -r requirements.txt || true ;
  - echo "Dependencies should be sane now."
  - travis_retry pip install tox || pip install tox || true ;
  - travis_retry python3 -m pip install tox || python3 -m pip install tox || travis_retry python3 -m pip --user install tox || python3 -m pip install --user --upgrade tox || true ;
  - travis_retry python -m pip install tox || python -m pip install tox || travis_retry python -m pip install --user tox || python -m pip install --upgrade --user tox || true ;
  - if [ $TRAVIS_OS_NAME != osx ] ; then curl --tlsv1.2 -s -o archive.tar.bz2 https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.2.tar.bz2 && tar xjf archive.tar.bz2 --directory / || true ; fi
  - pip install tox || pip install --upgrade tox || true ;
  - travis_retry python3 -m pip3 install coverage || python3 -m pip3 install coverage || travis_retry python3 -m pip3 install --user coverage || python3 -m pip3 install --upgrade --user coverage || true ;
  - travis_retry python3 -m pip3 install codecov || python3 -m pip3 install codecov || true ;
  - travis_retry pip install flake8 || travis_retry python3 -m pip3 install flake8 || travis_retry python3 -m pip3 install --user flake8 || true ;
  - travis_retry pip install flake || true ;
  - travis_retry pip install codecov || true ;
  - sudo mkdir -p -m 775 "/opt/PiAP/"
  - sudo chown -v $USER "/opt/PiAP/" || echo "TEST WILL FAIL DUE TO PERMISSIONS" ;
  - mkdir -p -m 755 "/opt/PiAP/hostapd_actions/" || true
  - chmod -v 775 "/opt/PiAP/" || true
  - cp -vf ./units/PiAP-python-tools/tests/mock/clients /opt/PiAP/hostapd_actions/clients || true
  - cp -vf ./units/PiAP-python-tools/tests/mock/dnsmasq.leases /var/lib/misc/dnsmasq.leases || true
  - make -C ./units/PiAP-python-tools/ -f Makefile Makefile mock-config || true
  - rm -vf /opt/PiAP/.beta_* 2>/dev/null || true ;
  - sync || true ;
  - echo "travis_fold:end:piap_setup" 2>/dev/null || true

install:
  - make clean || true

before_script:
  - make clean ;
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter 2>/dev/null || true
  - chmod +x ./cc-test-reporter 2>/dev/null || true
  - ./cc-test-reporter before-build 2>/dev/null || true

script:
  - echo "travis_fold:start:piap_test" 2>/dev/null || true
  - make test || export TRAVIS_TEST_RESULT=$? ;
  - echo "travis_fold:end:piap_test" 2>/dev/null || true
  - echo "travis_fold:start:piap_codecov" 2>/dev/null || true
  - codecov || true
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 2>/dev/null || true ; fi
  - echo "travis_fold:end:piap_codecov" 2>/dev/null || true
  - make clean || export TRAVIS_TEST_RESULT=$? ;
  - if [ $TRAVIS_OS_NAME != osx ] ; then travis_retry make test-tox ; fi
  - make clean 2>/dev/null || true ;

after_success:
  - codecov 2>/dev/null || true
  - python3 -m piaplib.pocket book version --verbose --all 2>/dev/null || python -m piaplib.pocket book version --verbose --all 2>/dev/null
  - uname

after_failure:
  - python3 -m piaplib.pocket book version --verbose --all 2>/dev/null || python -m piaplib.pocket book version --verbose --all 2>/dev/null || true
  - uname
