#! /bin/bash
umask 027

# this should not run predictably
date $(date -R -r $(curl -fsLj --header "Dnt: 1" --url "https://time.is/Unix_time_now" 2>/dev/null 3>/dev/null | grep -F '<time id="clock">' | grep -oE "[>]{1}[0-9]+[<]{1}" | grep -oE "[0-9]+" ) | cut -d, -f 2 )

exit 0 ;
