version: 2
jobs:
  build:
    working_directory: ~/Pocket-PiAP
    docker:
      - image: circleci/buildpack-deps:latest
        environment:
          CI: cicleci
          DEBIAN_FRONTEND: noninteractive
          LANG: en_US.UTF-8
          SHELL: /bin/bash
    steps:
      - run:
          name: "update apt"
          command: |
            sudo apt-get -yq update ; wait ;
      - run:
          name: "upgrade apt"
          command: |
            sudo apt-get -yq dist-upgrade || sudo apt-get -f -y dist-upgrade ; wait ;
      - run:
          name: "install dependencies"
          command: |
            sudo apt-get -y install build-essential make git gnupg2 nginx nginx-full php-fpm dnsmasq hostapd python3 python3-pip ; wait ;
      - checkout
      - run:
          shell: /bin/bash
          name: "fetch and pull"
          command: |
            git fetch && git pull --all && (git submodule init || true ) && git submodule update --remote --checkout && git submodule foreach git fetch --all || true
      - run:
          name: "clean apt"
          command: |
            sudo apt-get autoclean ; wait ;
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean || true
      - run:
          name: "fetch not pull"
          command: |
            curl -fsSL --tlsv1.2 --url https://raw.githubusercontent.com/reactive-firewall/Pocket-PiAP/${CIRCLE_SHA1:-stable}/upgrade.sh -o ~/Pocket-PiAP/upgrade.sh 2>/dev/null || true
      - run:
          shell: /bin/bash
          name: "Install path Tests"
          command: |
            export PIAP_UI_BRANCH="${CIRCLE_BRANCH:-${CIRCLE_SHA1:-master}}" && sudo bash ~/Pocket-PiAP/upgrade.sh || true
      - run:
          shell: /bin/bash
          name: "CWE-501 into CWE-250 attempt"
          command: |
            sudo usermod -a -G pocket,pocket-admin circleci || true
      - run:
          shell: /bin/bash
          name: "Break ACL for circle to bootstrap tests"
          command: |
            sudo chmod -v 775 /opt/PiAP/ || true
      - run:
          shell: /bin/bash
          name: "UnBreak old tests"
          command: |
            sudo rm -vf /opt/PiAP/.beta_* 2>/dev/null || true
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean
destination: build
