#! /bin/bash
# Disclaimer of Warranties.
# A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
#    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
#    BY OR ACCESSED THROUGH THIS SHELL SCRIPT IS AT YOUR SOLE RISK AND
#    THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
#    EFFORT IS WITH YOU.
#
# B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
#    AND SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND
#    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT AND PIAP TOOL'S LICENSORS
#    (COLLECTIVELY REFERRED TO AS "THE AUTHOR OF PIAP" FOR THE PURPOSES OF THIS DISCLAIMER)
#    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
#    SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
#    NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF
#    MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
#    ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.
#
# C. THE AUTHOR OF PIAP DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE
#    THE AUTHOR OF PIAP SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN, OR
#    SERVICES PERFORMED OR PROVIDED BY, THIS SHELL SCRIPT WILL MEET YOUR
#    REQUIREMENTS, THAT THE OPERATION OF THIS SHELL SCRIPT OR SERVICES WILL
#    BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICES WILL CONTINUE TO BE MADE
#    AVAILABLE, THAT THIS SHELL SCRIPT OR SERVICES WILL BE COMPATIBLE OR
#    WORK WITH ANY THIRD PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES,
#    OR THAT DEFECTS IN THIS SHELL SCRIPT OR SERVICES WILL BE CORRECTED.
#    INSTALLATION OF THIS THE AUTHOR OF PIAP SOFTWARE MAY AFFECT THE USABILITY OF THIRD
#    PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES.
#
# D. YOU FURTHER ACKNOWLEDGE THAT THIS SHELL SCRIPT AND SERVICES ARE NOT
#    INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE
#    OR TIME DELAYS OF, OR ERRORS OR INACCURACIES IN, THE CONTENT, DATA OR
#    INFORMATION PROVIDED BY THIS SHELL SCRIPT OR SERVICES COULD LEAD TO
#    DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE,
#    INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
#    NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR
#    WEAPONS SYSTEMS.
#
# E. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY THE AUTHOR OF PIAP
#    SHALL CREATE A WARRANTY. SHOULD THIS SHELL SCRIPT OR SERVICES PROVE DEFECTIVE,
#    YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#    Limitation of Liability.
# F. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHOR OF PIAP
#    BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR
#    CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES
#    FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR
#    RECEIVE ANY DATA OR INFORMATION, BUSINESS INTERRUPTION OR ANY OTHER
#    COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR
#    INABILITY TO USE THIS SHELL SCRIPT OR SERVICES OR ANY THIRD PARTY
#    SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH THIS SHELL SCRIPT OR
#    SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
#    TORT OR OTHERWISE) AND EVEN IF THE AUTHOR OF PIAP HAS BEEN ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION
#    OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR
#    CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event
#    shall pak tool's total liability to you for all damages (other than as may
#    be required by applicable law in cases involving personal injury) exceed
#    the amount of five dollars ($5.00). The foregoing limitations will apply
#    even if the above stated remedy fails of its essential purpose.
################################################################################

umask 137
PATH="/bin/:/usr/bin/:/usr/sbin/:/sbin/:/usr/local/bin/:/usr/local/sbin/"
export PATH="${PATH}:/opt/PiAP/bin/:/opt/PiAP/sbin/"

/opt/PiAP/bin/set_LED_status_Xmas.bash 2>/dev/null || true ; wait ;

HAS_POCKET_USER=$(id pocket-www 1>&2 2>/dev/null >> /dev/null && echo -n 0 || echo -n $?)
POCKET_WEB_USER="www-data"
if [[ ( ${HAS_POCKET_USER:-1} -lt 1 ) ]] ; then 
        POCKET_WEB_USER="pocket-www"
fi
/opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; wait ;

LOCK_FILE="/tmp/PiAP_scan_mode_Throttle_lock"

if [[ -f ${LOCK_FILE} ]] ; then
	# need to add targets to a queue here
        exit 0 ;
fi

/opt/PiAP/bin/set_LED_status_Xmas.bash 2>/dev/null || true ; wait ;

trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 1 ;' SIGKILL
trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 1 ;' SIGHUP
trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 1 ;' SIGTERM
trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 1 ;' SIGQUIT
trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 1 ;' SIGINT
trap 'rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; /opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ; exit 0 ;' EXIT

touch ${LOCK_FILE} 2>/dev/null || exit 0 ;


/etc/init.d/fw scanmode || /etc/init.d/fw stop || exit 1 ;
/opt/PiAP/bin/set_LED_status_Agro.bash || true ;
#nmap --privileged -sT -p T:80,443,43,53,22,21,20,993,25,8080,138,139,17500 -g 5353 --reason --data-length $(((${RANDOM}%100)+63)) $@
#sleep 3s ; wait ;
#nmap --privileged -sU -p U:80,443,53,123,67,68,995 -g 5353 --reason --data-length $(((${RANDOM}%100)+56)) $@
#sleep 1s ; wait ;
#nmap --privileged -PN -A -F --reason --data-length $(((${RANDOM}%100)+70)) $@
SCAN_NAME=$(echo "$@" | grepip | sort -t \. -n | uniq | head -n 1 )
nmap --privileged -PN -A --script='safe and discovery or vuln' -T4 --reason --data-length $(((${RANDOM}%100)+70)) -oX /tmp/scan_${SCAN_NAME:-latest}.xml $@ || true ;
/etc/init.d/fw start ; wait ;
/opt/PiAP/bin/set_LED_status_Xmas.bash 2>/dev/null || true ;
umask 0007
if [[ !( -d /srv/PiAP/files/scans/ ) ]] ; then mkdir -m 751 -p /srv/PiAP/files/scans 2>/dev/null ; wait ; chown -vf ${POCKET_WEB_USER:-0}:${POCKET_WEB_USER:-www-data} /srv/PiAP/files/scans/ ; wait ; fi ;
if [[ ( -f /srv/PiAP/files/scans/scan_${SCAN_NAME:-latest}.xml ) ]] ; then
head -n 999999 /tmp/scan_${SCAN_NAME:-latest}.xml 2>/dev/null | tee -a /srv/PiAP/files/scans/scan_${SCAN_NAME:-latest}.xml 2>/dev/null ; wait ;
else
mv -f /tmp/scan_${SCAN_NAME:-latest}.xml /srv/PiAP/files/scans/scan_${SCAN_NAME:-latest}.xml 2>/dev/null || true ; wait ;
chown ${POCKET_WEB_USER:-0}:${POCKET_WEB_USER:-www-data} /srv/PiAP/files/scans/scan_${SCAN_NAME:-latest}.xml || true ; wait ;
chmod 640 /srv/PiAP/files/scans/scan_${SCAN_NAME:-latest}.xml || true
fi
umask 137

rm -f ${LOCK_FILE} 2>/dev/null || true ;
/opt/PiAP/bin/set_LED_status_Ready.bash 2>/dev/null || true ;

exit 0;
