#! /bin/bash
# Disclaimer of Warranties.
# A. YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT, TO THE EXTENT PERMITTED BY
#    APPLICABLE LAW, USE OF THIS SHELL SCRIPT AND ANY SERVICES PERFORMED
#    BY OR ACCESSED THROUGH THIS SHELL SCRIPT IS AT YOUR SOLE RISK AND
#    THAT THE ENTIRE RISK AS TO SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
#    EFFORT IS WITH YOU.
#
# B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
#    AND SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND
#    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT AND PIAP TOOL'S LICENSORS
#    (COLLECTIVELY REFERRED TO AS "THE AUTHOR OF PIAP" FOR THE PURPOSES OF THIS DISCLAIMER)
#    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
#    SOFTWARE AND SERVICES, EITHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
#    NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF
#    MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
#    ACCURACY, QUIET ENJOYMENT, AND NON-INFRINGEMENT OF THIRD PARTY RIGHTS.
#
# C. THE AUTHOR OF PIAP DOES NOT WARRANT AGAINST INTERFERENCE WITH YOUR ENJOYMENT OF THE
#    THE AUTHOR OF PIAP SOFTWARE AND SERVICES, THAT THE FUNCTIONS CONTAINED IN, OR
#    SERVICES PERFORMED OR PROVIDED BY, THIS SHELL SCRIPT WILL MEET YOUR
#    REQUIREMENTS, THAT THE OPERATION OF THIS SHELL SCRIPT OR SERVICES WILL
#    BE UNINTERRUPTED OR ERROR-FREE, THAT ANY SERVICES WILL CONTINUE TO BE MADE
#    AVAILABLE, THAT THIS SHELL SCRIPT OR SERVICES WILL BE COMPATIBLE OR
#    WORK WITH ANY THIRD PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES,
#    OR THAT DEFECTS IN THIS SHELL SCRIPT OR SERVICES WILL BE CORRECTED.
#    INSTALLATION OF THIS THE AUTHOR OF PIAP SOFTWARE MAY AFFECT THE USABILITY OF THIRD
#    PARTY SOFTWARE, APPLICATIONS OR THIRD PARTY SERVICES.
#
# D. YOU FURTHER ACKNOWLEDGE THAT THIS SHELL SCRIPT AND SERVICES ARE NOT
#    INTENDED OR SUITABLE FOR USE IN SITUATIONS OR ENVIRONMENTS WHERE THE FAILURE
#    OR TIME DELAYS OF, OR ERRORS OR INACCURACIES IN, THE CONTENT, DATA OR
#    INFORMATION PROVIDED BY THIS SHELL SCRIPT OR SERVICES COULD LEAD TO
#    DEATH, PERSONAL INJURY, OR SEVERE PHYSICAL OR ENVIRONMENTAL DAMAGE,
#    INCLUDING WITHOUT LIMITATION THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
#    NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, LIFE SUPPORT OR
#    WEAPONS SYSTEMS.
#
# E. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY THE AUTHOR OF PIAP
#    SHALL CREATE A WARRANTY. SHOULD THIS SHELL SCRIPT OR SERVICES PROVE DEFECTIVE,
#    YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
#
#    Limitation of Liability.
# F. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHOR OF PIAP
#    BE LIABLE FOR PERSONAL INJURY, OR ANY INCIDENTAL, SPECIAL, INDIRECT OR
#    CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES
#    FOR LOSS OF PROFITS, CORRUPTION OR LOSS OF DATA, FAILURE TO TRANSMIT OR
#    RECEIVE ANY DATA OR INFORMATION, BUSINESS INTERRUPTION OR ANY OTHER
#    COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR
#    INABILITY TO USE THIS SHELL SCRIPT OR SERVICES OR ANY THIRD PARTY
#    SOFTWARE OR APPLICATIONS IN CONJUNCTION WITH THIS SHELL SCRIPT OR
#    SERVICES, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT,
#    TORT OR OTHERWISE) AND EVEN IF THE AUTHOR OF PIAP HAS BEEN ADVISED OF THE
#    POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION
#    OR LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR
#    CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event
#    shall pak tool's total liability to you for all damages (other than as may
#    be required by applicable law in cases involving personal injury) exceed
#    the amount of five dollars ($5.00). The foregoing limitations will apply
#    even if the above stated remedy fails of its essential purpose.
################################################################################

# PROOF OF CONCEPT - NEED TO DEBUG before use

ulimit -t 300
umask 137
PATH="/bin:/sbin:/usr/sbin:/usr/bin"
#
# USER_ID - the user id used for the certificate
USER_ID=$(/srv/PiAP/dsauth.py -C -f /srv/PiAP/files/db/passwd -X $(sudo -u pocket-www head -n 1 /srv/PiAP/files/db/pepper) -U ${1} )
# Create the Client Key and CSR
LINK_STUB_PATH="/srv/PiAP/files/x509/${USER_ID:-client}"
FILE_STUB_PATH="/etc/ssl/PiAPCA/certs/${USER_ID:-client}"
mkdir -p /srv/PiAP/files/x509 || true
mkdir -p /etc/ssl/PiAPCA/certs || true
# CWE-20 if this admin tool is exposed directly
CN_USERNAME="${1:-operator}"
rm -f ${FILE_STUB_PATH:-client}.key || true
rm -f ${FILE_STUB_PATH:-client}.pem || true
openssl genrsa -out ${FILE_STUB_PATH:-client}.key 2048
openssl req -new -key ${FILE_STUB_PATH:-client}.key -subj "/CN=${CN_USERNAME}/OU=Client/O=PiAP\ Network/" -out ${FILE_STUB_PATH:-client}.csr
openssl ca -config /etc/ssl/PiAP_keyring.cfg -days 365 -in ${FILE_STUB_PATH:-client}.csr -extfile /etc/ssl/PiAP_keyring.cfg -extensions client_cert | fgrep --after-context=900 -e $"-----BEGIN CERTIFICATE-----" | sudo tee -a ${FILE_STUB_PATH:-client}.pem
OPENSSL_CONF=/etc/ssl/PiAP_keyring.cfg openssl pkcs12 -export -in ${FILE_STUB_PATH}.pem -inkey ${FILE_STUB_PATH:-client}.key -out ${FILE_STUB_PATH}.p12 -chain -CAfile /etc/ssl/certs/ssl-cert-nginx.pem -nodes -name "${1}" || EXIT_CODE=2

cp -f ${FILE_STUB_PATH}.p12 ${LINK_STUB_PATH}.p12
cp -f ${FILE_STUB_PATH}.pem ${LINK_STUB_PATH}.pem
sudo chown pocket-admin:pocket-www ${LINK_STUB_PATH}.p* 2>/dev/null > /dev/null || true
sudo chmod 640 ${LINK_STUB_PATH}.p* 2>/dev/null > /dev/null || true

shred --zero ${FILE_STUB_PATH:-client}.key || true
rm -f ${FILE_STUB_PATH:-client}.key || true

exit ${EXIT_CODE:-0} ;
